name: Deploy to Loucka Proxmox

on:
  push:
    branches: [ master ]  # Spustí se při každém pushi (i z práce)

jobs:
  deploy:
    runs-on: self-hosted  # Tohle zacílí na tvůj běžící runner
    steps:
      - name: Update local repository
        run: |
          # Přejdeme do složky s repozitářem (uprav cestu, pokud je jinde)
          cd /home/runner/weewx-belchertown-new
          git pull origin master


      - name: Copy Python extensions (bin/user)
        run: |
          # Kopírování obsahu bin/user do systémové složky WeeWX
          # Používáme sudo, protože do /etc/weewx/bin/user obvykle runner nemůže zapisovat
          # -a: zachová práva, -v: vypíše co dělá, --delete: smaže ve WeeWX to, co jsi smazal v Gitu
          sudo rsync -av /home/runner/weewx-belchertown-new/bin/user/ /etc/weewx/bin/user/

      - name: Copy Skin files (skins/Belchertown)
        run: |
          # Kopírování obsahu složky skinu
          sudo rsync -av --delete /home/runner/weewx-belchertown-new/skins/Belchertown/ /etc/weewx/skins/Belchertown/

      - name: Force WeeWX to generate report
        run: |
          sudo weectl report run 
